### ISSUE TITLE
[Client] 주변 정보 가져오기

### ISSUE THREAD

**Issue by 3000-2** [codestates/Tip-Talk#109]
### **ISSUE**

- Group: `client`
- Type: `feature`
- Detail: 주변 정보 가져오기

### **TODO**

- [x]  주변 정보 가져오기
- [x]  해당 위치에 마커 표시
- [x]  마커 클릭 이벤트 구현
