### ISSUE TITLE
[Client] 단순 버그 수정

### ISSUE THREAD

**Issue by 3000-2** [codestates/Tip-Talk#120]
### **ISSUE**

- Group: `client`
- Type: `fix`
- Detail: 단순 버그 수정

### **TODO**

- [x]  토큰 만기시 스토리지 토큰 제거
- [x]  카테고리 변수명 오류 수정
- [x]  업로드 페이지에서 이미지 삭제시 발생하는 에러 수정
