### ISSUE TITLE
[Server] 오작동 및 버그 수정

### ISSUE THREAD

**Issue by 3000-2** [codestates/Tip-Talk#121]
### **ISSUE**

- Group: `server`
- Type: `fix`
- Detail: 오작동 및 버그 수정

### **TODO**

- [x]  비밀번호가 틀려도 로그인 되는 에러 수정
- [x]  category DB 관계 재설정
- [x]  getPosts 응답데이터 수정
