### ISSUE TITLE
[Client & Server] 버그 수정

### ISSUE THREAD

**Issue by ghost** [codestates/Tip-Talk#177]
### **ISSUE**

- Group: `client`
- Type: `bug`
- Detail: 버그 수정

### **TODO**

- [x]  소셜 로그인했을 때 닉네임 수정이 원활하지 않던 버그 수정
- [x]  수정하기 버튼 눌렀을 때 모달 안 뜨는 버그 수정
- [x]  게시글에 이미지가 여러 장이면 제대로 표시되지 않던 버그 수정
