### ISSUE TITLE
[SR] 시스템 아키텍처 설계 및 스키마 작성

### ISSUE THREAD

**Issue by 3000-2** [codestates/Tip-Talk#3]
### **ISSUE**

- Group: `sr`
- Type: 
- Detail: 시스템 아키텍처 설계 및 스키마 작성, API 문서 작성

### **TODO**

- [x]  시스템 아키텍처 설계
- [x]  DB 스키마 작성
- [x]  API 문서 작성
